Use smaller integer in wiicode/http.c's timeout
    wiicode/http.c: In function 'http_request':
    wiicode/http.c:331:4: error: large integer implicitly
        truncated to unsigned type

This error is because the paramater is a u16, and it is being passed a value
that is greater than 2^16.  Instead use 2^15, as this is still a decent
timeout.

This change only affects Wii code.